-- AlterEnum
-- Thêm loại nghiệp vụ Phiếu chi nhập tay (§5 tiền mặt) — 8 loại.
ALTER TYPE "CashVoucherCategory" ADD VALUE IF NOT EXISTS 'PAYMENT_EMPLOYEE_ADVANCE';
ALTER TYPE "CashVoucherCategory" ADD VALUE IF NOT EXISTS 'PAYMENT_SUPPLIER';
ALTER TYPE "CashVoucherCategory" ADD VALUE IF NOT EXISTS 'PAYMENT_PURCHASE_WITH_INVOICE';
ALTER TYPE "CashVoucherCategory" ADD VALUE IF NOT EXISTS 'PAYMENT_SALARY_ADVANCE';
ALTER TYPE "CashVoucherCategory" ADD VALUE IF NOT EXISTS 'PAYMENT_SALARY';
ALTER TYPE "CashVoucherCategory" ADD VALUE IF NOT EXISTS 'PAYMENT_TO_BRANCH';
ALTER TYPE "CashVoucherCategory" ADD VALUE IF NOT EXISTS 'PAYMENT_LOAN';
ALTER TYPE "CashVoucherCategory" ADD VALUE IF NOT EXISTS 'PAYMENT_CIT_TAX';
